# Generated by Django 4.0.1 on 2022-01-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruser', '0002_alter_pruser_username_alter_pruser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pruser',
            options={'verbose_name': '프로젝트 사용자', 'verbose_name_plural': '프로젝트 사용자'},
        ),
        migrations.AddField(
            model_name='pruser',
            name='useremail',
            field=models.CharField(default='test@gamil.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pruser',
            name='registered_dttm',
            field=models.DateTimeField(auto_now_add=True, verbose_name='등록시간'),
        ),
    ]
