# Generated by Django 4.0.1 on 2022-01-19 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='pr1_tag',
        ),
    ]
